# Generated by Django 6.1 on 2026-09-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_eagles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('wing', models.CharField(choices=[('GE', 'Green Eagles Crew'), ('MOP', 'Messengers of Peace'), ('BOTH', 'Both Wings')], default='GE', max_length=10)),
                ('role', models.CharField(choices=[('MEMBER', 'Volunteer / Scout Member'), ('PATROL_LEADER', 'Patrol Leader'), ('COORDINATOR', 'Wing Coordinator'), ('EXEC', 'Executive Admin')], default='MEMBER', max_length=20)),
                ('patrol_name', models.CharField(blank=True, help_text='e.g. Rhino Patrol, Eagle Patrol', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
