# Generated by Django 6.1 on 2026-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_eagles', '0002_memberprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
