# Generated by Django 5.2.17 on 2026-09-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_eagles', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_wing',
            field=models.CharField(choices=[('ALL', 'All Wings (Central)'), ('GE', 'Green Eagles Crew Only'), ('MOP', 'Messengers of Peace Only')], default='ALL', max_length=10),
        ),
    ]
